### ISSUE TITLE
Twitch API v5

### ISSUE THREAD

**Issue by mfiorenza** [begs/livestreamers#4]
Twitch API v3 shut down a few days ago and your live.py script no longer works.

Your script does send the header to request v5, but it doesn't do it properly.

Currently:
`curl	-s 'Accept: application/vnd.twitchtv.v5+json' `

Fix:
`curl	-s -H 'Accept: application/vnd.twitchtv.v5+json' `

Need to add the -H flag to send it as part of the header.

**Comment by begs** [comment]
Thanks for the heads up, I just fixed it.
