### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by ewokninja** [begs/livestreamers#5]
I've recently started getting a `KeyError` when running the script. I'm only a dabbler in python and scripting but based on taking a look at the json returned by curl it seems that twitch is no longer returning `_total` which is causing the try on line 19 to fail? Hope this information/report is helpful - I find this script very useful!

**Comment by begs** [comment]
Hey,
It looks like Twitch removed the "_total" datafield from the list of streams. I just fixed it :)

I'm glad you are enjoying the script!
