### ISSUE TITLE
Error - make sure your OAuth is formatted correctly in oauth.txt

### ISSUE THREAD

**Issue by danglingptr0x0** [begs/livestreamers#6]
It would appear that this no longer works due to the API changes. I've verified that the OAuth token is formatted correctly.

**Comment by begs** [comment]
I'll rewrite this for the new API soon!

**Comment by danglingptr0x0** [comment]
> I'll rewrite this for the new API soon!

Much appreciated!

**Comment by begs** [comment]
Done!

**Comment by danglingptr0x0** [comment]
> Done!

Yooo! Thanks, man.
